"""Add title column to applications

Revision ID: 01535ffc2383
Revises: 
Create Date: 2025-11-03 00:16:02.010604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01535ffc2383'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    with op.batch_alter_table('coverletters', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverletters', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
