"""Change resume content_url to content text

Revision ID: 9cb0446603ca
Revises: e6bbed0cad5a
Create Date: 2026-01-03 11:04:27.619577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb0446603ca'
down_revision = 'e6bbed0cad5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.drop_column('content_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
