"""Remove no column from users

Revision ID: fa0e1b81fe37
Revises: 01535ffc2383
Create Date: 2025-11-03 10:13:06.053875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0e1b81fe37'
down_revision = '01535ffc2383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_no_key'), type_='unique')
        batch_op.drop_column('no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('users_no_key'), ['no'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
